### ISSUE TITLE
mv-edit-min/max changes are not picked up

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/mavo#527]
Probably there is no mutation observer on all `mv-edit-*` attributes so changes to them are not picked up and applied to the editor.

**Comment by DmitrySharabin** [comment]
What about this one?
https://codepen.io/dsharabin/pen/VOQvxY?editors=1000

**Comment by LeaVerou** [comment]
Thank you! It's certainly better than no testcase, but a simpler testcase would probably involve a slider or number input.

**Comment by DmitrySharabin** [comment]
Yes, mine definitely is not the reduced one. 😅 I've never been one for the easy way out, but I'm working on it.

**Comment by LeaVerou** [comment]
Simpler testcase: https://codepen.io/pen?template=gxPjmz&editors=1100#0

**Comment by LeaVerou** [comment]
So I just pushed a partial (?) fix for this (which also makes every `mv-edit-` attribute live). However, there is a caveat.
On a range input, this will work as you might expect, and you get the handle actually moving as you change the min/max. It also works as you'd expect on Dmitry's date testcase.
However, on a number input, nothing happens. But this is not due to Mavo, but due to how number inputs work. E.g. if you have `<input type="number" value="10" min="20" />`, the value will not be coerced to 20. Instead, if you try to edit it, that's when the constraint gets enforced.
I'm leaning towards closing this issue, but wanted a second opinion.

**Comment by DmitrySharabin** [comment]
> Simpler testcase: https://codepen.io/pen?template=gxPjmz&editors=1100#0

I believe this might be the link to a template, not the pen with the testcase.

**Comment by LeaVerou** [comment]
Oops, updated!

**Comment by DmitrySharabin** [comment]
> I'm leaning towards closing this issue, but wanted a second opinion.

I'm for it. Unfortunately, I still can't see new features in the dev version. So these testcases still don't work as we expect. What am I doing wrong?

**Comment by karger** [comment]
I'm not sure what I'm seeing or what I'm supposed to see in this testcase.

**Comment by DmitrySharabin** [comment]
> I'm not sure what I'm seeing or what I'm supposed to see in this testcase.

I think we face the same issue: the new dev version (that includes the latest commits) haven't been built. That's why we can't see what Lea sees.

**Comment by LeaVerou** [comment]
Oops, deploys have been failing for several commits now. On it.

**Comment by LeaVerou** [comment]
Deploys are live again! I was using async arrow functions which weren't supported by Netlify's default Node version. I now explicitly specified the Node version to build with and everything is back to normal.
However, it does mean that the dev version suddenly got a bunch of new commits, so the chances of regressions are high. Please check all your apps!
