### ISSUE TITLE
Invalid property id in mavo.js

### ISSUE THREAD

**Issue by joyously** [mavoweb/mavo#569]
Back in January, I opened an issue showing a problem with a Mavo in SeaMonkey. See https://github.com/LeaVerou/markapp/issues/60
More recently, I was going to work on my test site which has two Mavo tests and both were getting a JS error in Mavo, and I hadn't changed them at all since they were working.

Today, I wanted to start back into Mavo, but the Mavo demo pages were not working for me in SeaMonkey. 
![mavo-demo-not-working](https://user-images.githubusercontent.com/7957680/73896607-17f58400-4849-11ea-9b2d-c82e1db58951.jpg)

There seems to have been a change in Mavo that works in Firefox, but not in SeaMonkey. Shouldn't this stuff work in most browsers? It was working before in SeaMonkey.

**Comment by joyously** [comment]
Looking at the code on line 8481, it says 
`      ...callback`
so I think it's the `...` that is the problem in SeaMonkey.

**Comment by LeaVerou** [comment]
Are you on a recent version of SeaMonkey? Which rendering engine does it use?

If the problem is `...`, I'm not sure we can refactor the entire Mavo codebase because SeaMonkey doesn't support `...` yet.

> Shouldn't this stuff work in most browsers?

Most, yes, but it's impossible to support *all*. As much as we would love to, there are tradeoffs. The market share of SeaMonkey is currently less than 0.01%, and it's difficult to find how much less. It's not even listed in [StatCounter's CSV](https://gs.statcounter.com/browser-market-share/all/) and is listed as 0.00% [here](https://www.netmarketshare.com/browser-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Custom%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browser%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktop%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222018-01%22%2C%22dateEnd%22%3A%222018-01%22%2C%22pageLength%22%3A50%2C%22segments%22%3A%22-1000%22%7D), which is for 2018. For 2020, it's not even listed.

**However, I notice you're using mavo.js. If the problem is indeed ES6, using mavo.es5.js should alleviate it.**

**Comment by joyously** [comment]
OK, it's not about SeaMonkey itself, but older browsers in general. 
And it's not really refactoring the entire Mavo codebase either, because it used to work in this same version of SeaMonkey. It's only recently that `...` was added and it doesn't work. I didn't change anything on my end, for my tests, and the screenshot above is from your own demo site.
So are you saying that as a Mavo user, I have to use something like Modernizer to see which Mavo JS file to load? I never saw that in the documentation. I certainly can't predict what browser my visitors might use, and apparently you can't predict it either, since the demo loads mavo.js.

**Comment by LeaVerou** [comment]
Nope, no conditional loading required. We recommend using `mavo.es5.js` for everyone if you need wider browser support that includes older/more obscure browsers. :)
I believe we've been using `...` for a long time, pretty much once support for it reached a certain threshold, but perhaps not from the beginning. 

I'm going to leave this issue open in case `mavo.es5.js` doesn't fix the problem, so we can debug further.

**Comment by joyously** [comment]
How would I use that in your demo? or on the markapp page?

**Comment by joyously** [comment]
I tried my local test with mavo.es5.js and it worked.
It seems to me that this is not a decision a Mavo user should have to make. The target market of Mavo is people that don't code, so it would make more sense if the file that they include does the test for compatibility and loads the appropriate main Mavo file. If not that, at least the error should be caught and a message about upgrading their browser could be output.
Otherwise, using Mavo on a site runs the risk of showing broken empty pages, like your demo site and markapp page. That's not a very good advertisement of Mavo.

**Comment by LeaVerou** [comment]
Please note that many libraries *only* distribute a transpiled version, we provide users the option and make it very clear in the [download page](https://mavo.io/get) what the tradeoffs are.
Browsers that need `mavo.es5.js` ovr `mavo.js` today are fairly rare, around < 3% all together.

Thank you for your input. I'm going to go ahead and close this now, since your issue is resolved.

**Comment by joyously** [comment]
I see your point, but my issue is still not resolved. I can't see the demo or the markapp page in my preferred browser.
Also, that download page has a bug when trying to choose a specific version (or that just my old browser?).

**Comment by joyously** [comment]
Just for completeness, this problem for me is the spread operator in object literals. It doesn't have as much support as other uses of the spread operator. https://www.caniuse.com/#feat=mdn-javascript_operators_spread_spread_in_object_literals

My SeaMonkey is equivalent to Firefox 52, and the chart shows support started in Firefox 55 and Chrome 60.  That's not that long ago (2017).
